config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :you do
    resources :albums do
      resources :songs, except: %i[index show]
    end
  end

  scope module: 'public' do
    resources :albums, only: %i[index show] do
      resources :songs, only: %i[index show]
    end
  end

  root 'public/pages#home'
end

app/models/album.rb
# frozen_string_literal: true

# Represents a album of a product.
class Album < ApplicationRecord
  has_one_attached :cover, dependent: :destroy do |attachable|
    attachable.variant :player, resize: '80x80'
    attachable.variant :thumb, resize: '100x100'
    attachable.variant :medium, resize: '400x400'
  end

  # Associations
  has_many :songs, dependent: :destroy

  # Validations
  validates :title, :artist_name, presence: true
  # validates :cover, presence: true
  validates :cover, attached: true,
    content_type: ['image/png', 'image/jpeg', 'image/gif'],
    aspect_ratio: :square,
    dimension: { 
      width: { min: 400, max: 1200 },
      height: { min: 400, max: 1200 }
    }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/song.rb
# frozen_string_literal: true

# Model Song
class Song < ApplicationRecord
  # Callbacks
  before_save :year_from_album

  # Attachments
  has_one_attached :audio, dependent: :destroy

  # Associations
  belongs_to :album

  # Scopes
  scope :ordered, -> { order(disk_number: :asc, track_number: :asc) }

  # delegation
  delegate :artist_name, to: :album

  # Validations
  validates :title, presence: true
  validates :audio, blob: { content_type: %w[audio/mpeg] }

  def previous
    album.songs.ordered.where('track_number < ?', track_number).where(disk_number:).last
  end

  private

  def year_from_album
    return if year != 0

    self.year = album.release_date.year
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/you/albums_controller.rb
# frozen_string_literal: true

module You
  # Controller class to CRUD actions of Ablums
  class AlbumsController < ApplicationController
    before_action :set_album, only: %i[show edit update destroy]

    # GET /albums
    def index
      @albums = Album.all
    end

    # GET /albums/1
    def show; end

    # GET /albums/new
    def new
      @album = Album.new
    end

    # GET /albums/1/edit
    def edit; end

    # POST /albums
    def create
      @album = Album.new(album_params)

      if @album.save
        redirect_to [:you, @album], notice: t('you.albums.created')
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /albums/1
    def update
      if @album.update(album_params)
        redirect_to [:you, @album], notice: t('you.albums.updated'), status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /albums/1
    def destroy
      @album.destroy!
      redirect_to you_albums_url, notice: t('you.albums.destroyed'), status: :see_other
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(%i[title upc artist_name label release_date cover])
    end
  end
end

app/controllers/you/songs_controller.rb
# frozen_string_literal: true

module You
  # Controller for CRUD actions of songs
  class SongsController < ApplicationController
    before_action :set_album
    before_action :set_song, only: %i[edit update destroy]

    # GET /songs/new
    def new
      @song = ::Songs::BuildSong.run(album: @album).result
    end

    # GET /songs/1/edit
    def edit; end

    # POST /songs
    def create
      @song = @album.songs.new(song_params)

      if @song.save
        respond_to do |format|
          format.html { redirect_to [:you, @album], notice: t('private.songs.created') }
          format.turbo_stream { flash.now[:notice] = t('private.songs.created') }
        end
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /songs/1
    def update
      if @song.update(song_params)
        respond_to do |format|
          format.html { redirect_to [:you, @album], notice: t('private.songs.updated'), status: :see_other }
          format.turbo_stream { flash.now[:notice] = t('private.songs.updated') }
        end
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /songs/1
    def destroy
      @song.destroy!
      redirect_to you_songs_url, notice: t('private.songs.destroyed'), status: :see_other
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = @album.songs.find(params[:id])
    end

    def set_album
      @album = Album.find(params[:album_id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:album_id, :title, :isrc, :track_number, :disk_number, :comment, :composer, :audio)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/albums/_album.html.slim
.cover.mb-4
  - if album.cover.attached? && album.cover.attachment.blob.present? && album.cover.attachment.blob.persisted?
    = image_tag album.cover.variant(:medium)
.info.bg-stone-800.text-stone-100.py-2.px-4
  .grid.grid-cols-2
    .text-sm.font-bold UPC
    - if album.upc.empty?
      .text-end  --
    - else
      .text-end =< album.upc
    .text-sm.font-bold Artist Name
    .text-end = album.artist_name
    .text-sm.font-bold Label
    .text-end = album.label
    .text-sm.font-bold Release data
    - if album.release_date.nil?
      .text-sm.text-end --/--/----
    - else
      .text-sm.text-end =< album.release_date.to_fs(:short_date)

app/views/albums/_form.html.slim
= simple_form_for(@album, multipart: true) do |form|
  - if album.errors.any?
    div.mb-5 style="color: red"
      h2 = "#{pluralize(album.errors.count, "error")} prohibited this album from being saved:"
      ul
        - album.errors.each do |error|
          li = error.full_message

  .grid.grid-cols-3.gap-4
    = render "image_preview", form: form, album: album
    .text-help.px-4.pt-5
      p El arte de la portada debe ser un archivo .jpg o .png cuadrado y debe ser mínimo de 3000x3000 px, máximo de 6000x6000 px, no borroso ni pixelado.

      p.mt-4.font-bold No puede contener:
      ul.list-disc.px-8.italic
        li Logotipos de redes sociales.
        li Logotipos de marcas.
        li Cualquier texto excepto nombres de artistas y / o el nombre del lanzamiento.
      p.mt-4 Si contiene algo de lo anterior, tu lanzamiento será rechazado (estas normas las establecen las tiendas y tenemos que cumplirlas).

    .fields.pt-5
      = form.input :title,
              input_html: { class: 'w-full' },
              label_html: { class: 'block' },
              wrapper_html: { class: 'mb-5'}

      = form.input :artist_name,
              input_html: { class: 'w-full' },
              label_html: { class: 'block' },
              wrapper_html: { class: 'mb-5' }

      = form.input :label,
              input_html: { class: 'w-full' },
              label_html: { class: 'block' },
              wrapper_html: { class: 'mb-5'}

      div.mb-5
        = form.input :upc,
                input_html: { class: 'w-full disabled:bg-gray-50' },
                label_html: { class: 'block' },
                wrapper_html: { class: 'mb-5' }

      div.mb-5
        = form.label :release_date, style: "display: block"
        = form.date_field :release_date, class: 'w-full'

  div.text-end
    = form.submit class: 'bg-stone-800 text-stone-100 p-2 hover:bg-stone-400 px-5 py-3 cursor-pointer'

app/views/albums/edit.html.slim
.flex.flex-shrink
  .lg:flex-grow
    h1.text-3xl.font-bold.text-stone-600.text-stone-600.relative.top-2 = t('private.releases.edit.title')
  .flex.block.text-end.border-t.inline-block.align-middle.mt-2
    = link_to "Back to Albums", :back, class: 'bg-stone-800 text-stone-100 p-2 hover:bg-red-400'

== render "form", album: @album

br

div
  => link_to "Show this album", @album
  '|
  =< link_to "Back to albums", albums_path

app/views/albums/new.html.slim
.flex.flex-shrink
  .lg:flex-grow
    h1.text-3xl.font-bold.text-stone-600.text-stone-600.relative.top-2 = t('private.albums.new.title')
  .flex.block.text-end.border-t.inline-block.align-middle.mt-2
    = link_to "Back to Albums", :back, class: 'bg-stone-800 text-stone-100 p-2 hover:bg-red-400'

.mb-5
== render "form", album: @album

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Taggin
    meta[name="viewport" content="width=device-width,initial-scale=1"]
      = csrf_meta_tags
      = csp_meta_tag
      = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
      = stylesheet_link_tag "application", "data-turbo-track": "reload"
      = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"

  body
    = render 'shared/navbar'

    main.container.mx-auto.max-w-7xl.px-4.py-24.sm:px-6.sm:py-24.lg:px-8
      = yield

app/views/pages/home.html.slim
div
  h1.font-bold.text-4xl
    | Pages#home
  p
    | Find me in app/views/pages/home.html.erb

app/views/releases/_form.html.slim
= simple_form_for(@release, multipart: true) do |form|
  - if release.errors.any?
    div.mb-5 style="color: red"
      h2 = "#{pluralize(release.errors.count, "error")} prohibited this release from being saved:"
      ul
        - release.errors.each do |error|
          li = error.full_message

  .grid.grid-cols-3.gap-4
    = render "image_preview", form: form, release: release
    .text-help.px-4.pt-5
      p El arte de la portada debe ser un archivo .jpg o .png cuadrado y debe ser mínimo de 3000x3000 px, máximo de 6000x6000 px, no borroso ni pixelado.

      p.mt-4.font-bold No puede contener:
      ul.list-disc.px-8.italic
        li Logotipos de redes sociales.
        li Logotipos de marcas.
        li Cualquier texto excepto nombres de artistas y / o el nombre del lanzamiento.
      p.mt-4 Si contiene algo de lo anterior, tu lanzamiento será rechazado (estas normas las establecen las tiendas y tenemos que cumplirlas).

    .fields.pt-5
      = form.input :title,
              input_html: { class: 'w-full' },
              label_html: { class: 'block' },
              wrapper_html: { class: 'mb-5'}

      = form.input :artist_name,
              input_html: { class: 'w-full' },
              label_html: { class: 'block' },
              wrapper_html: { class: 'mb-5' }

      = form.input :label,
              input_html: { class: 'w-full' },
              label_html: { class: 'block' },
              wrapper_html: { class: 'mb-5'}

      - if !@release.new_record?
        div.mb-5
          = form.input :upc,
                  input_html: { class: 'w-full disabled:bg-gray-50' },
                  label_html: { class: 'block' },
                  wrapper_html: { class: 'mb-5' }

      div.mb-5
        = form.label :release_date, style: "display: block"
        = form.date_field :release_date, class: 'w-full'

  div.text-end
    = form.submit class: 'bg-stone-800 text-stone-100 p-2 hover:bg-stone-400 px-5 py-3 cursor-pointer'

app/views/releases/_image_preview.html.slim
div data-controller="previews"
  = form.label :cover, style: "display: block"
  = form.file_field :cover, direct_upload: true, multiple: false, class: 'hidden',
          data: { previews_target: "input", action: "change->previews#preview" }
  .cover-container.border.border-dashed.border-gray-900/25 data-action="click->previews#click"
    - if @release.cover.attached?
      = image_tag release.cover.variant(:medium), data: { previews_target: "preview" }, class: 'image', width: 400
    - else
      = image_tag "", data: { previews_target: "preview" }, class: "image", width: 400

app/views/shared/_flash.html.slim
- flash.each do |flash_type, message|
  div class="flash__message" data-controller="removals" data-action="animationend->removals#remove"
    = message

app/views/shared/_navbar.html.slim
header.bg-white
  nav.mx-auto.flex.max-w-7xl.items-center.justify-between.p-6.lg:px-8[ariel-label='Global']
    .flex.lg:flex-1
      = link_to '/', class: '-m-1.5 p-1.5' do
        span.sr-only Taggin
        span.font-bold.uppercase Taggin

    .flex.lg:hidden
      button type='button' class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
        span.sr-only Open main menu
        svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon"
          path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"

    .hidden.lg:flex.lg:gap-x-12
      .relative
      = link_to t('navbar.albums'), albums_path, class: 'text-sm font-semibold leading-6 text-gray-900'

    .hidden.lg:flex.lg:flex-1.lg:justify-end
      = link_to '#', class: 'text-sm font-semibold leading-6 text-gray-900' do
        = t('navbar.loggin')
        span aria-hidden="true"

app/views/shared/_player.html.slim
.fixed.bg-blacky.w-full.bottom-0.left-0.text-white
  .container.mx-auto.max-w-7xl.px-4.py-1.sm:px-6
    div.grid.grid-cols-2
      .info.flex
        = image_tag @album.cover.variant(:player), class: 'px-2'
        ul.into-txt
          li[data-sound-target='title'] = 'Song Title'
          li = @album.artist_name
          li = @album.title

      .controls
        button[type="button" data-action="sound#backward" class="m-2 hover:text-yellow-500"]
          svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-8 h-8"
            path stroke-linecap="round" stroke-linejoin="round" d="M21 16.811c0 .864-.933 1.406-1.683.977l-7.108-4.061a1.125 1.125 0 0 1 0-1.954l7.108-4.061A1.125 1.125 0 0 1 21 8.689v8.122ZM11.25 16.811c0 .864-.933 1.406-1.683.977l-7.108-4.061a1.125 1.125 0 0 1 0-1.954l7.108-4.061a1.125 1.125 0 0 1 1.683.977v8.122Z"

        button[type="button" data-action="sound#playToggle" data-sound-target='play' class="me-2  hover:text-yellow-500"]
          svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-8 h-8"

        button[type="button" data-action="sound#stop" class="m-2 hover:text-yellow-500"]
          svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-8 h-8"
            path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
            path stroke-linecap="round" stroke-linejoin="round" d="M9 9.563C9 9.252 9.252 9 9.563 9h4.874c.311 0 .563.252.563.563v4.874c0 .311-.252.563-.563.563H9.564A.562.562 0 0 1 9 14.437V9.564Z"

        button[type="button" data-action="sound#next" class="mx-2 hover:text-yellow-500"]
          svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-8 h-8"
            path stroke-linecap="round" stroke-linejoin="round" d="M3 8.689c0-.864.933-1.406 1.683-.977l7.108 4.061a1.125 1.125 0 0 1 0 1.954l-7.108 4.061A1.125 1.125 0 0 1 3 16.811V8.69ZM12.75 8.689c0-.864.933-1.406 1.683-.977l7.108 4.061a1.125 1.125 0 0 1 0 1.954l-7.108 4.061a1.125 1.125 0 0 1-1.683-.977V8.69Z"

        button[type="button" data-action="sound#muteToggle" data-sound-muted-param="false" data-sound-target='mute' class='me-2 hover:text-yellow-500']
          svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"

app/views/songs/_form.html.slim
= simple_form_for [@album, @song] do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :isrc
    .grid.grid-cols-2.gap-4
      = f.input :track_number
      = f.input :disk_number
    = f.input :year
    = f.input :comment
    = f.input :composer
    = f.input :audio, as: :file
    p.mt-1.text-sm.text-gray-500.dark:text-gray-300 File uploaded: #{@song.audio&.blob&.filename || ''}

  .text-end.mt-5
    = link_to 'Cancel', @album, class: 'inline-block my-2 bg-stone-200 hover:bg-red-600 hover:text-white text-sm py-2 px-4 p-3 mr-3'
    = f.button :button, as: :submit, class: 'p-3'

app/views/songs/_song.html.slim
= turbo_frame_tag song do
  div.bg-stone-100.p-6.mb-2
    = turbo_frame_tag dom_id(song, :edit) do
      h3.font-bold.text-lg
        span.text-yellow-400 = format '%02d.', song.track_number
        span.ml-2 #{song.title}
      .text-sm.text-stone-600
        span = song.album.artist_name
        span.mx-2 -
        span = song.album.title
      - if !song.isrc.blank?
        p
          strong ISRC
          =< song.isrc
      - if !song.comment.blank?
        .my-2
          h5.text-stone-800.font-bold.text-xs Comment:
          =< song.comment
      - if !song.composer.blank?
        .my-2
          h5.text-stone-800.font-bold.text-xs Composer:
          =< song.composer

      .grid.grid-cols-2.mt-6
        .mini-player.flex
          button[type="button" data-action="sound#playPosition" data-sound-position-param='#{song.track_number - 1}' class="me-2 align-middle"]
            svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"
              path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
              path stroke-linecap="round" stroke-linejoin="round" d="M15.91 11.672a.375.375 0 0 1 0 .656l-5.603 3.113a.375.375 0 0 1-.557-.328V8.887c0-.286.307-.466.557-.327l5.603 3.112Z"

          div
            - if song.audio.attached?
              span.text-sm = song.audio.blob.filename
              audio[src="#{rails_blob_url(song.audio)}" data-sound-name="#{song.title}" data-sound-target="audios"]


        .text-end
          => link_to 'Edit this song', edit_album_song_path(album, song),
                  class: 'bg-stone-200 hover:bg-stone-400 hover:text-white text-sm p-3'

app/views/songs/edit.html.slim
h1 Editing song

= turbo_frame_tag dom_id(@song, :edit) do
  = render "form", album: @album, song: @song

div
  = link_to "Back to album", @album

app/views/you/albums/_album.html.slim
.cover.mb-4
  - if album.cover.attached? && album.cover.attachment.blob.present? && album.cover.attachment.blob.persisted?
    = image_tag album.cover.variant(:medium)

.info.bg-stone-800.text-stone-100.py-2.px-4
  .grid.grid-cols-2
    .text-sm.font-bold = t('activerecord.attributes.album.upc')
    - if album.upc.empty?
      .text-end  --
    - else
      .text-end =< album.upc
    .text-sm.font-bold = t('activerecord.attributes.album.artist_name')
    .text-end = album.artist_name
    .text-sm.font-bold = t('activerecord.attributes.album.label')
    .text-end = album.label
    .text-sm.font-bold = t('activerecord.attributes.album.release_date')
    - if album.release_date.nil?
      .text-sm.text-end --/--/----
    - else
      .text-sm.text-end =< album.release_date.to_fs(:short_date)

app/views/you/albums/_form.html.slim
= simple_form_for([:you, @album], multipart: true) do |form|
  - if album.errors.any?
    div.mb-5 style="color: red"
      h2 = "#{pluralize(album.errors.count, "error")} prohibited this album from being saved:"
      ul
        - album.errors.each do |error|
          li = error.full_message

  .grid.grid-cols-3.gap-4
    = render "image_preview", form: form, album: album
    .text-help.px-4.pt-5
      p El arte de la portada debe ser un archivo .jpg o .png cuadrado y debe ser mínimo de 3000x3000 px, máximo de 6000x6000 px, no borroso ni pixelado.

      p.mt-4.font-bold No puede contener:
      ul.list-disc.px-8.italic
        li Logotipos de redes sociales.
        li Logotipos de marcas.
        li Cualquier texto excepto nombres de artistas y / o el nombre del lanzamiento.
      p.mt-4 Si contiene algo de lo anterior, tu lanzamiento será rechazado (estas normas las establecen las tiendas y tenemos que cumplirlas).

    .fields.pt-5
      = form.input :title,
              input_html: { class: 'w-full' },
              label_html: { class: 'block' },
              wrapper_html: { class: 'mb-5'}

      = form.input :artist_name,
              input_html: { class: 'w-full' },
              label_html: { class: 'block' },
              wrapper_html: { class: 'mb-5' }

      = form.input :label,
              input_html: { class: 'w-full' },
              label_html: { class: 'block' },
              wrapper_html: { class: 'mb-5'}

      div.mb-5
        = form.input :upc,
                input_html: { class: 'w-full disabled:bg-gray-50' },
                label_html: { class: 'block' },
                wrapper_html: { class: 'mb-5' }

      div.mb-5
        = form.label :release_date, style: "display: block"
        = form.date_field :release_date, class: 'w-full'

  div.text-end
    = form.submit class: 'bg-stone-800 text-stone-100 p-2 hover:bg-stone-400 px-5 py-3 cursor-pointer'

app/views/you/albums/edit.html.slim
.flex.flex-shrink
  .lg:flex-grow
    h1.text-3xl.font-bold.text-stone-600.text-stone-600.relative.top-2 = t('you.albums.edit.title')
  .flex.block.text-end.border-t.inline-block.align-middle.mt-2
    = link_to 'Back to Albums', :back, class: 'bg-stone-800 text-stone-100 p-2 hover:bg-red-400'

== render 'you/albums/form', album: @album

br

div
  => link_to 'Show this album', [:you, @album]
  '|
  =< link_to 'Back to albums', you_albums_path

app/views/you/albums/index.html.slim
p style="color: green" = notice

.flex.flex-shrink
  .lg:flex-grow
    h1.text-3xl.font-bold.text-stone-600.text-stone-600.relative.top-2  = t('you.albums.index.title')
  .flex.block.text-end.border-t.inline-block.align-middle.mt-2
    = link_to "New album", new_you_album_path, class: 'block bg-stone-800 text-stone-100 p-2 hover:bg-stone-400'

#albums.grid.grid-cols-3.gap-5
  - @albums.each do |album|
    .bg-stone-800.text-stone-100 id="#{dom_id album}"
      == render 'you/albums/album', album: album
      .mt-5.text-center
        = link_to "Show this album", [:you, album], class: 'block p-3 hover:bg-stone-700'

app/views/you/albums/show.html.slim
p style="color: green" = notice

h1.text-3xl.font-bold.text-stone-800.mb-8 =< @album.title

div[data-controller="sound" ]
  .text-end.mb-5
    = link_to "Back to albums", you_albums_path, class: 'bg-stone-800 text-stone-100 p-2 hover:bg-stone-600 p-3 mb-3 mr-3'
    = link_to new_you_album_song_path(@album),
            data: { turbo_frame: dom_id(::Songs::BuildSong.run(album: @album).result) },
            class: 'bg-stone-800 text-stone-100 p-2 hover:bg-green-700 p-3 mb-3' do
      svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline-block"
        path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15"
      span New Song

  .grid class="grid-cols-[30%_70%]"
    .column.bg-stone-800.text-stone-100.mb-2
      == render @album
      .actions.mt-5.text-center
        => link_to "Edit this album", edit_you_album_path(@album), class: 'underline-offset-1 hover:underline p-2'
        '|
        = button_to "Destroy this album", [:you, @album], method: :delete, class: 'inline-block underline-offset-1 hover:underline hover:text-red-600 p-2', form_class: 'inline-block'
    .column.pl-10
      = turbo_frame_tag ::Songs::BuildSong.run(album: @album).result
      = turbo_frame_tag 'songs' do
        = render @album.songs.ordered, album: @album

  == render 'shared/player'

app/views/you/songs/_song.html.slim
= turbo_frame_tag song do
  div.bg-stone-100.p-6.mb-2
    = turbo_frame_tag dom_id(song, :edit) do
      h3.font-bold.text-lg
        span.text-yellow-400 = format '%02d.', song.track_number
        span.ml-2 #{song.title}
      .text-sm.text-stone-600
        span = song.album.artist_name
        span.mx-2 -
        span = song.album.title
      - if !song.isrc.blank?
        p
          strong = t('activerecord.attributes.song.isrc') + ':'
          =< song.isrc
      - if !song.comment.blank?
        .my-2
          h5.text-stone-800.font-bold.text-xs = t('activerecord.attributes.song.comment') + ':'
          =< song.comment
      - if !song.composer.blank?
        .my-2
          h5.text-stone-800.font-bold.text-xs = t('activerecord.attributes.song.composer') + ':'
          =< song.composer

      .grid.grid-cols-2.mt-6
        .mini-player.flex
          button[type="button" data-action="sound#playPosition" data-sound-position-param='#{song.track_number - 1}' class="me-2 align-middle"]
            svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"
              path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
              path stroke-linecap="round" stroke-linejoin="round" d="M15.91 11.672a.375.375 0 0 1 0 .656l-5.603 3.113a.375.375 0 0 1-.557-.328V8.887c0-.286.307-.466.557-.327l5.603 3.112Z"

          div
            - if song.audio.attached?
              span.text-sm = song.audio.blob.filename
              audio[src="#{rails_blob_url(song.audio)}" data-sound-name="#{song.title}" data-sound-target="audios"]


        .text-end
          => link_to 'Edit this song', edit_you_album_song_path(album, song),
                  class: 'bg-stone-200 hover:bg-stone-400 hover:text-white text-sm p-3'

app/views/you/songs/edit.html.slim
h1 = t('.title')

= turbo_frame_tag dom_id(@song, :edit) do
  = render "form", album: @album, song: @song

div
  = link_to "Back to album", [:you, @album]

app/views/you/songs/index.html.slim
p style="color: green" = notice

h1 Songs

#songs
  - @songs.each do |song|
    == render song
    p
      = link_to "Show this song", song

= link_to "New song", new_song_path

app/views/you/songs/new.html.slim
h1 New song

= turbo_frame_tag @song do
  .bg-stone-100.p-6.mb-2
    == render "form", song: @song

/ div
/   = link_to "Back to songs", songs_path

app/views/you/songs/show.html.slim
p style="color: green" = notice

== render @song

div
  => link_to "Edit this song", edit_album_song_path(@album, @song)
  '|
  =< link_to "Back to songs", album_path(@album)

  = button_to "Destroy this song", @song, method: :delete